In [1]:
import numpy as np
def normalize(x):
    fac = abs(x).max()
    x_n = x/ x.max()
    return fac, x_n
x = np.array([1,1,1])
a=np.array([[151 ,146 ,160 ],[77 ,86 ,116 ],[52 ,74 ,80]])

for i in range (8):
    x = np.dot(a,x)
    lambda_1,x=normalize(x)

print("Eigen Value : ", lambda_1)
print("Eigen Vector : ",x)

Eigen Value :  303.6182800180198
Eigen Vector :  [1.         0.5801133  0.42451085]


In [2]:
import numpy as np
from numpy.linalg import inv
def normalize(x):
    fac = abs(x).max()
    x_n = x/ x.max()
    return fac, x_n
a=np.array([[151 ,146 ,160 ],[77 ,86 ,116 ],[52 ,74 ,80]])
x = np.array([1,1,1])
inv_a = inv(a)
for i in range (8):
    x = np.dot(inv_a,x)
    lambda_1,x=normalize(x)
print("Eigen Value  = ",lambda_1)
print("Eigen Vector = ", x)

Eigen Value  =  0.09117329621033295
Eigen Vector =  [ 0.30827259 -1.44106108  1.        ]


In [3]:
import numpy as np
def normalize(x):
    fac = abs(x).max()
    x_n = x/ x.max()
    return fac, x_n
x = np.array([1,1,1])
A = np.array([[151, 146, 160, 166, 177, 188, 162, 168, 168],
              [77, 86, 116, 142, 148, 150, 142, 140, 123],
              [52, 74, 80, 89, 127, 111, 131, 127, 63],
              [65, 69, 95, 71, 97, 98, 104, 72, 48],
              [95, 50, 89, 68, 65, 59, 45, 55, 76],
              [95, 59, 88, 69, 33, 36, 40, 64, 94],
              [87, 73, 98, 76, 90, 90, 74, 58, 45],
              [69, 74, 78, 86, 136, 138, 137, 86, 44],
              [67, 74, 92, 98, 92, 107, 106, 132, 96]])
matrix_list = [A[i:i+3, j:j+3] for i in range(0, 9, 3) for j in range(0, 9, 3)]
eigenvalues_list = []
eigenvectors_list = []

for matrix in matrix_list:
    x = np.array([1,1,1])
    for i in range (8):
        x = np.dot(matrix,x)
        lambda_1,x=normalize(x)
    eigenvalues_list.append(lambda_1)
    eigenvectors_list.append(x)

for i, matrix in enumerate(matrix_list):
    print(f"Matrixatrix {i+1}:")
    print(f"Eigenvalues:\n{eigenvalues_list[i]}")
    print(f"Eigenvectors:\n{eigenvectors_list[i]}\n")

Matrixatrix 1:
Eigenvalues:
303.6182800180198
Eigenvectors:
[1.         0.5801133  0.42451085]

Matrixatrix 2:
Eigenvalues:
428.7666137597263
Eigenvectors:
[1.         0.83332353 0.61312951]

Matrixatrix 3:
Eigenvalues:
413.1694713244069
Eigenvectors:
[1.         0.82260739 0.67244906]

Matrixatrix 4:
Eigenvalues:
235.29546067425724
Eigenvectors:
[0.94976366 0.96725277 1.        ]

Matrixatrix 5:
Eigenvalues:
200.09918521883827
Eigenvectors:
[1.         0.75310142 0.57192406]

Matrixatrix 6:
Eigenvalues:
198.98387102948305
Eigenvectors:
[1.         0.75737499 0.84273879]

Matrixatrix 7:
Eigenvalues:
237.05828143136185
Eigenvectors:
[1.         0.85202509 0.89653521]

Matrixatrix 8:
Eigenvalues:
307.19871170455366
Eigenvectors:
[0.70191923 1.         0.80314245]

Matrixatrix 9:
Eigenvalues:
244.45606407721783
Eigenvectors:
[0.50790107 0.7168072  1.        ]



In [4]:
import numpy as np
from numpy.linalg import inv
def normalize(x):
    fac = abs(x).max()
    x_n = x/ x.max()
    return fac, x_n
x = np.array([1,1,1])
A = np.array([[151, 146, 160, 166, 177, 188, 162, 168, 168],
              [77, 86, 116, 142, 148, 150, 142, 140, 123],
              [52, 74, 80, 89, 127, 111, 131, 127, 63],
              [65, 69, 95, 71, 97, 98, 104, 72, 48],
              [95, 50, 89, 68, 65, 59, 45, 55, 76],
              [95, 59, 88, 69, 33, 36, 40, 64, 94],
              [87, 73, 98, 76, 90, 90, 74, 58, 45],
              [69, 74, 78, 86, 136, 138, 137, 86, 44],
              [67, 74, 92, 98, 92, 107, 106, 132, 96]])
matrix_list = [A[i:i+3, j:j+3] for i in range(0, 9, 3) for j in range(0, 9, 3)]
eigenvalues_list = []
eigenvectors_list = []

for matrix in matrix_list:
    x = np.array([1,1,1])
    inv_a = inv(matrix)
    for i in range (8):
        x = np.dot(inv_a,x)
        lambda_1,x=normalize(x)
    eigenvalues_list.append(lambda_1)
    eigenvectors_list.append(x)

for i, matrix in enumerate(matrix_list):
    print(f"Matrixatrix {i+1}:")
    print(f"Eigenvalues:\n{eigenvalues_list[i]}")
    print(f"Eigenvectors:\n{eigenvectors_list[i]}\n")

Matrixatrix 1:
Eigenvalues:
0.09117329621033295
Eigenvectors:
[ 0.30827259 -1.44106108  1.        ]

Matrixatrix 2:
Eigenvalues:
0.058143926818074745
Eigenvectors:
[-0.25057969  1.         -0.78828565]

Matrixatrix 3:
Eigenvalues:
0.40095644998657537
Eigenvectors:
[-0.92058743  1.         -0.09744524]

Matrixatrix 4:
Eigenvalues:
0.20410320958563571
Eigenvectors:
[ 0.32613887  1.         -0.96686035]

Matrixatrix 5:
Eigenvalues:
0.20316552671700577
Eigenvectors:
[ 0.05346031 -1.04658673  1.        ]

Matrixatrix 6:
Eigenvalues:
1.1083712668490242
Eigenvectors:
[-0.46536486  1.         -0.47322533]

Matrixatrix 7:
Eigenvalues:
0.12197057225875496
Eigenvectors:
[-0.85063952 -0.36227639  1.        ]

Matrixatrix 8:
Eigenvalues:
0.16673978720238045
Eigenvectors:
[-0.0195196   1.         -0.92988366]

Matrixatrix 9:
Eigenvalues:
0.03491411813043758
Eigenvectors:
[-0.58732856  1.         -0.42814026]

